default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: afri_eats_development
  host: localhost
  username: alex
  password: alex

test:
  <<: *default
  database: afri_eats_test
  host: localhost
  username: alex
  password: alex

production:
  <<: *default
  database: afri_eats_production
  host: localhost
  username: alex
  password: <%= ENV["afri_eats_PASSWORD"] %>

